metatags:
  favicon:
    image: favicon.png
  title:
    only: true
theme:
  - fontawesome
taxonomies:
  categories: disabled
  tags: disabled
pages:
  pagination:
    enabled: false
  default:
    xsl/atom:
      published: false
    xsl/rss:
      published: false
output:
  pagetypeformats:
    homepage: html
