pages:
  default:
    manifest:
      path: manifest
      output: webmanifest
    serviceworker:
      path: serviceworker
      layout: serviceworker
      output: js
      multilingual: false
      serviceworker:
        precache: false
manifest:
  background_color: '#FFFFFF'
  theme_color: '#202020'
  icons:
    - icon-192x192.png
    - icon-512x512.png
    - src: icon-192x192-maskable.png
      purpose: maskable
    - src: icon-512x512-maskable.png
      purpose: maskable
  shortcuts: false
serviceworker:
  enabled: false
  notification:
    enabled: false
    message: 'Website updated since your last visit.'
